services:
  dapp-homepage:
    build: .
    container_name: dapp-homepage
    environment:
      PORT: "8000"
      VIRTUAL_HOST: testnet-mini-apps.usernodelabs.org
      VIRTUAL_PORT: "8000"
      LETSENCRYPT_HOST: testnet-mini-apps.usernodelabs.org
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true

